"use server";

import { auth } from "@/auth";
import { db } from "@/lib/db";
import {
  getAttemptPaper as getPaper,
  logEvent,
  saveResponse as save,
  startAttempt as start,
  submitAttempt as submit,
} from "@/lib/exam/attempt";
import {
  ExamEventSeverity,
  ExamEventType,
  ExamSubmittedBy,
  type PrismaClient,
} from "@prisma/client";
import { headers } from "next/headers";

/**
 * Exam Center — sitting an exam.
 *
 * Authorisation and request plumbing only; the engine is in lib/exam/attempt.ts.
 *
 * Note there is no `revalidatePath` anywhere in this file. An exam in progress is
 * driven by client state against a server-authoritative clock — busting the route
 * cache mid-answer would throw away the candidate's unsaved input.
 */

const prisma = db as PrismaClient;

async function requireUser(): Promise<
  { ok: true; userId: string } | { ok: false; error: string }
> {
  const session = await auth();
  if (!session?.user?.id) return { ok: false, error: "Unauthorized" };
  return { ok: true, userId: session.user.id };
}

/** Best-effort client IP, for the integrity log only. */
async function clientIp(): Promise<string | null> {
  try {
    const h = await headers();
    return (
      h.get("x-forwarded-for")?.split(",")[0]?.trim() ?? h.get("x-real-ip") ?? null
    );
  } catch {
    return null;
  }
}

/**
 * Enter an exam, or resume an attempt already in progress.
 *
 * `deviceToken` is generated by the client and persisted for the duration of the
 * sitting; it is what lets a reconnect be told apart from a second device.
 */
export async function startExamAttempt(
  examId: string,
  input: { accessCode?: string; deviceToken?: string } = {},
) {
  const user = await requireUser();
  if (!user.ok) return { error: user.error };

  const h = await headers().catch(() => null);

  const result = await start(
    examId,
    user.userId,
    {
      accessCode: input.accessCode ?? null,
      deviceToken: input.deviceToken ?? null,
      ipAddress: await clientIp(),
      userAgent: h?.get("user-agent") ?? null,
    },
    prisma,
  );

  if (!result.ok) return { error: result.error, code: result.code };

  return {
    success: true,
    attemptId: result.attemptId,
    resumed: result.resumed,
    expiresAt: result.expiresAt,
    serverTime: new Date(),
    questionCount: result.questionCount,
  };
}

/** The paper as the candidate may see it — never includes correct answers. */
export async function getExamPaper(attemptId: string) {
  const user = await requireUser();
  if (!user.ok) return { error: user.error };

  const result = await getPaper(attemptId, user.userId, prisma);
  if (!result.ok) return { error: result.error, code: result.code };

  return {
    success: true,
    attemptId: result.attemptId,
    expiresAt: result.expiresAt,
    serverTime: result.serverTime,
    status: result.status,
    questions: result.questions,
  };
}

/** Autosave a single answer. Safe to call on every keystroke or selection. */
export async function saveExamResponse(input: {
  attemptId: string;
  questionId: string;
  answer: unknown;
  clientSavedAt?: string | number | Date | null;
  isFlagged?: boolean;
}) {
  const user = await requireUser();
  if (!user.ok) return { error: user.error };

  const result = await save(
    input.attemptId,
    user.userId,
    input.questionId,
    input.answer,
    {
      clientSavedAt: input.clientSavedAt ? new Date(input.clientSavedAt) : null,
      isFlagged: input.isFlagged,
    },
    prisma,
  );

  if (!result.ok) return { error: result.error, code: result.code };
  return { success: true, savedAt: result.savedAt, stale: result.stale ?? false };
}

/** Submit. Idempotent — a retry returns the same grade rather than a second one. */
export async function submitExamAttempt(attemptId: string) {
  const user = await requireUser();
  if (!user.ok) return { error: user.error };

  const attempt = await prisma.examAttempt.findUnique({
    where: { id: attemptId },
    select: { userId: true },
  });
  if (!attempt) return { error: "Attempt not found" };
  if (attempt.userId !== user.userId) return { error: "Unauthorized" };

  const result = await submit(attemptId, ExamSubmittedBy.STUDENT, prisma);
  if (!result.ok) return { error: result.error, code: result.code };

  return {
    success: true,
    alreadySubmitted: result.alreadySubmitted,
    pendingManual: result.pendingManual,
  };
}

/**
 * Record an integrity signal from the client.
 *
 * Always returns success: a failure here must never interrupt someone sitting an
 * exam. These are review flags, not enforcement.
 */
export async function recordExamEvent(input: {
  attemptId: string;
  type: keyof typeof ExamEventType;
  metadata?: Record<string, unknown>;
}) {
  const user = await requireUser();
  if (!user.ok) return { error: user.error };

  try {
    const attempt = await prisma.examAttempt.findUnique({
      where: { id: input.attemptId },
      select: { userId: true, examId: true },
    });
    if (!attempt || attempt.userId !== user.userId) return { success: true };

    const severity =
      input.type === "SECOND_DEVICE_BLOCKED" || input.type === "IP_CHANGED"
        ? ExamEventSeverity.WARNING
        : ExamEventSeverity.INFO;

    await logEvent(prisma, {
      attemptId: input.attemptId,
      examId: attempt.examId,
      userId: user.userId,
      type: ExamEventType[input.type],
      severity,
      metadata: (input.metadata ?? {}) as never,
      ipAddress: await clientIp(),
    });
  } catch {
    // Swallowed on purpose — see above.
  }

  return { success: true };
}
